config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'chat_rooms#index'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follows, :followers
    end
    member do
      get :destroy_all
    end
    member do
      get :check
    end
    resource :relationships, only: [:create, :destroy]
    resources :direct_rooms, only: [:new, :create, :destroy] do
      resources :direct_messages, only: [:index, :create]
    end
  end
  resources :chat_rooms do
    resource :bookmarks, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get :join
    end
    member do
      get :withdrawal
    end
    resources :chat_messages, only: [:index, :create]
  end
  resources :categories, only: [:index]
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
  has_one_attached :image, dependent: :destroy
  has_many :chat_room_users, dependent: :destroy
  has_many :users, through: :chat_room_users
  has_many :chat_messages, dependent: :destroy
  belongs_to :category, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :users_like, class_name: 'User', through: :likes
  has_many :notifications, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  validates :name,         presence: :true
  validates :introduction, presence: :true
  validates :genre_id    , presence: :true
  validates :owner_id    , presence: :true, numericality: { message: "が不正です" }
  validates :genre_id, numericality: { other_than: 1 , message: "が選択されていません" }

  def self.search(search)
    if search != ""
      ChatRoom.where('name LIKE(?)', "%#{search}%")
    else
      @chat_rooms = ChatRoom.includes(:users)
    end
  end

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  def liked?(user)
    likes.where(user_id: user.id).exists?
  end

  def create_notification_like!(current_user, user_id)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and chat_room_id = ? and action = ? ", current_user, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        chat_room_id: id,
        visited_id: user_id,
        action: 'like'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :join, :withdrawal]
  before_action :set_chat_room, only: [:show, :edit, :update]
  before_action :move_to_index, only: :edit

  def index
    @genres = Genre.where(:id => 2..8)
  end

  def new
    @chat_room_category = ChatRoomCategory.new
  end

  def create
    @chat_room_category = ChatRoomCategory.new(chat_room_category_params)
    if @chat_room_category.valid?
      @chat_room_category.save
      redirect_to root_path
      flash[:notice] = "チャットルームを投稿しました"
    else
      render :new
    end
  end

  def show
    @chat_room_user = ChatRoomUser.find_by(chat_room_id: params[:id])
    @user_joining = ChatRoomUser.where(user_id: params[:id])
  end

  def edit
  end  

  def update
    if @chat_room.update(chat_room_user_params)
      redirect_to chat_room_path
      flash[:notice] = "更新しました"
    else
      render :edit
    end
  end

  def destroy
    chat_room_user =ChatRoomUser.find(params[:id])
    @chat_room_user = chat_room_user.chat_room
    if @chat_room_user.destroy
      redirect_to root_path
      flash[:notice] = "チャットルームを削除しました"
    else
      render :show
    end
  end

  def join
    @chat_room = ChatRoom.find(params[:id])
    chat_room_user =ChatRoomUser.find_by(chat_room_id: params[:id])
    @chat_room_user = chat_room_user.chat_room
    @chat_room_user.users << current_user
    @chat_room_user.save
    redirect_to chat_room_chat_messages_path(@chat_room)
  end

  def withdrawal
    chat_room = ChatRoom.find(params[:id])
    chat_room_users =ChatRoomUser.where(user_id: current_user)
    chat_room_users.each do |chat_room_user|
      if chat_room.id == chat_room_user.chat_room.id
        chat_room_user.destroy
        flash[:notice] = "チャットルームから退出しました"
      end
    end
    if chat_room.owner_id == current_user.id
      chat_room.destroy
      redirect_to root_path
      flash[:notice] = "チャットルームを削除しました"
    else
      redirect_to root_path
    end
  end

  def search
    @genres = Genre.where(:id => 2..8)
    @chat_rooms = ChatRoom.search(params[:keyword])
  end

  private

  def chat_room_user_params
    params.require(:chat_room).permit(:name, :introduction, :genre_id, :image).merge(owner_id: current_user.id)
  end

  def chat_room_category_params
    params.require(:chat_room_category).permit(:name, :introduction, :genre_id, :image, :user_id, :owner_id).merge(user_id: current_user.id, owner_id: current_user.id)
  end

  def set_chat_room
    @chat_room = ChatRoom.find(params[:id])
  end

  def move_to_index
    @chat_room_user = ChatRoomUser.find_by(chat_room_id: params[:id])
    unless @chat_room_user.user == current_user
      redirect_to action: :index
    end
  end

end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/edit.html.erb
<%= render "shared/second-header"%>

<div class="container">
  <div class="room-main">
    <div class="heading-area">
      <div class="heading">ルーム編集</div>
    </div>
    <%= form_with model: @chat_room, url: chat_room_path, method: :patch, class: 'registration-from', local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class ="room-contents">
        <div class="room-filed">
          <p class="room-name-text">ルーム名</p>
          <span class="required">必須</span>
        </div>
      </div>
      <div class="input-name-area">
        <%= f.text_field :name, class:"room-name-input", placeholder:"ルーム名を記入して下さい", maxlength:"25" %>
      </div>
      <div class="select-area">
        <div class="select-inner">
          <p class="select-text">ルーム画像の設定</p>
          <span class="category-any">任意</span>
        </div>
        <div class="select-inner">
          <p class="select-text">カテゴリーの選択</p>
          <span class="required">必須</span>
        </div>
      </div>
      <div class ="category-area">
        <div class="select-image">
          <%= f.label :image, "画像をアップロード", class: "image-input-btn", id:"item-image"%>
          <%= f.file_field :image, class: "image-form"%>

        </div>
        <div class="categories">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>
        <div class="introduction">
          <p class="introduction-info">ルーム紹介</p>
          <span class="required">必須</span>
        </div>
        <div class="introduction-area">
            <%= f.text_area :introduction, class:"introduction-text", placeholder:"ルームの内容を記入して下さい" %>
        </div>
        <input name="chat_room_user[user_id]" type="hidden" value=<%= current_user.id %>>
        <div class="btn-area">
          <%= f.submit "更新する" ,class:"click-botton" %>
        </div>
    <% end %>
  </div>
</div>

app/views/chat_rooms/index.html.erb
<%= render "shared/header" %>

<div class="main">
  <div class="bg-image">
    <div class="heading-text">
      <p class="heading-top">簡単に!</p>
      <p class="heading-next">あっという間に！</p>
      <p>Shumitomoなら<span class="lead-text">共通の趣味</span>の友達を作れる</p>
      <%= image_tag("lead.png", class:"lead-img") %>
    </div>
  </div>
  <div class="wrapper">
    <div class="topics-contents">
      ★こんな方にオススメ★
    </div>
    <div class="topics-items">
      <div class="content">
        <%= image_tag("maigo.png", class:"item-image") %>
        <div class="info">知らない土地に転勤した方</div>
      </div>
      <div class="content">
        <%= image_tag("nayamu.png", class:"item-image") %>
        <div class="info">周りに共通の趣味を持った友達がいない方</div>
      </div>
      <div class="content">
        <%= image_tag("favorite.png", class:"item-image") %>
        <div class="info">趣味をもっと増やしたい方</div>
      </div>
    </div>
  </div>
  <div class="usage">
    <div class="usage-title">
      Shumitomoの使い方
    </div>
    <div class="procedure-contents">
      <ul>
        <li class="text"><span class="number">①</span>：まずはサイトに登録</li>
        <li class="text"><span class="number">②</span>：ルーム検索してチャットに参加<br>　※ルームを投稿して参加を待つのもアリ</li>
        <li class="text"><span class="number">③</span>：会話に参加して友達になろう！</li>
      </ul>
    </div>
    <% if user_signed_in? %>
      <div class="procedure-end-text">
        <%= link_to 'ルームを作る', new_chat_room_path, class: 'procedure-link' %>
      </div>
    <% else %>
       <div class="procedure-end-text">
        <%= link_to '新規登録はこちらから', new_user_registration_path, class: 'procedure-link' %>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/chat_rooms/new.html.erb
<%= render "shared/second-header"%>

<div class="container">
  <div class="room-main">
    <div class="heading-area">
      <div class="heading">ルーム作成</div>
    </div>
    <%= form_with model: @chat_room_category, url: chat_rooms_path, class: 'registration-from', local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class ="room-contents">
        <div class="room-filed">
          <p class="room-name-text">ルーム名</p>
          <span class="required">必須</span>
        </div>
      </div>
      <div class="input-name-area">
        <%= f.text_field :name, class:"room-name-input", placeholder:"ルーム名を記入して下さい", maxlength:"25" %>
      </div>
      <div class="select-area">
        <div class="select-inner">
          <p class="select-text">ルーム画像の設定</p>
          <span class="category-any">任意</span>
        </div>
        <div class="select-inner">
          <p class="select-text">カテゴリーの選択</p>
          <span class="required">必須</span>
        </div>
      </div>
      <div class ="category-area">
        <div class="select-image">
          <%= f.label :image, "画像をアップロード", class: "image-input-btn", id:"item-image"%>
          <%= f.file_field :image, class: "image-form"%>
        </div>
        <div class="categories">
          <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        </div>
      </div>
        <div class="introduction">
          <p class="introduction-info">ルーム紹介</p>
          <span class="required">必須</span>
        </div>
        <div class="introduction-area">
            <%= f.text_area :introduction, class:"introduction-text", placeholder:"ルームの内容を記入して下さい" %>
        </div>
        <input name="chat_room[user_id, owner_id][]" type="hidden" value=<%= current_user.id %>>
        <div class="btn-area">
          <%= f.submit "投稿する" ,class:"click-botton" %>
        </div>
    <% end %>
  </div>
</div>

app/views/chat_rooms/search.html.erb
<%= render "shared/header" %>

<div class="room-container">
  <% @chat_rooms.each_slice(3) do |chat_rooms| %>
    <div class="room-title-area">
      <% chat_rooms.each do |chat_room| %>
        <div class="contents">
          <div class= "room-title-lists">
            <ul>
              <li><%= link_to chat_room.name, chat_room_path(chat_room), class:"room-title-text", data: { 'turbolinks': false } %></li>
              <% if chat_room.image.present?%>
                <li>
                  <%= link_to chat_room_path(chat_room) do %>
                    <%= image_tag chat_room.image.variant(resize: '400x400'), class: "image" %>
                  <% end %>
                </li>
              <% else %>
                <%= link_to chat_room_path(chat_room), class:"image-list" do %>
                  <div class="image-list">
                    <p class="image-content">no<br>image<p>
                  </div>
                <% end %>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/chat_rooms/show.html.erb
<%= render "shared/second-header" %>
<div class="text-success-area">
  <span class="text-success"><%= flash[:notice] %></span>
</div>

<div class="container">
  <div class="room-main">
    <div class="user-count-area">
      現在<span class="users-count"><%= @chat_room.users.count %>名</span>のユーザーが参加しています
    </div>
    <div class="heading-area">
      <div class="heading">
        <%= @chat_room.name %>
      </div>
    </div>
    <div class="contributor-image-area">
      投稿者：<%= link_to @chat_room_user.user.nickname, user_path(@chat_room_user.user), class:"contributor-name", data: { 'turbolinks': false } %>
      <% if user_signed_in? %>
        <div class="menu-area">
          <p class="memu-text">Menu</p>
          <%= image_tag("menu.png", class:"menu-img", id:"menu") %>
          <div class="hidden" id="menu-list">
            <ul class="menu-list">
              <% if ChatRoomUser.exists?(chat_room_id: @chat_room.id, user_id: current_user.id) %>
                <li class="menu-btn"><%= link_to "入室", chat_room_chat_messages_path(@chat_room), class:"menu-text" %></li>
              <% end %>
              <% if current_user.id == @chat_room_user.user_id %>
                <li class="menu-btn"><%= link_to "編集", edit_chat_room_path(@chat_room), class:"menu-text" %></li>
                <li class="menu-btn"><%= link_to "削除", chat_room_path(@chat_room_user), method: :delete, class:"menu-text", id:"delete-btn", data: {confirm: "チャットルームを削除しますか？"}  %></li>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
      <% if @chat_room_user.chat_room.image.present? %>
        <div class="image-display">
          <div class="contributor-image-outer">
            <div class="image-item">
              <%= image_tag @chat_room_user.chat_room.image.variant(resize: '500x500'), class: "image-show" %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="image-nill-display">
            <div class="contributor-image-nill-outer">
              <p class="image-nill-room">no<br>image<p>
            </div>
        </div>
      <% end %>
    </div>
    <p class="contributor-introduction-text">ルーム紹介</p>
    <div class="profile-area">
      <div class="room-profile">
        <%= @chat_room_user.chat_room.introduction %>
      </div>
    </div>
    <div class="participate">
      <% if user_signed_in? %>
        <div class="btn-contents">
          <div class="likes" id="likes_button">
            <%= render partial: "shared/like", locals: { chat_room: @chat_room } %>
          </div>
          <% unless ChatRoomUser.exists?(chat_room_id: @chat_room.id, user_id: current_user.id) %>
            <div class="book-marks" id="bookmark_button">
              <%= render partial: "shared/book_mark", locals: { chat_room: @chat_room } %>
            </div>
          <% end %>
        </div>
        <% unless ChatRoomUser.exists?(chat_room_id: @chat_room.id, user_id: current_user.id) %>
        <div class="participate-area">
          <%= link_to "参加する", join_chat_room_path(@chat_room), class: "participate-btn", data: {confirm: "チャットルームに参加しますか"} %>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>