config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'chat_rooms#index'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follows, :followers
    end
    member do
      get :destroy_all
    end
    member do
      get :check
    end
    resource :relationships, only: [:create, :destroy]
    resources :direct_rooms, only: [:new, :create, :destroy] do
      resources :direct_messages, only: [:index, :create]
    end
  end
  resources :chat_rooms do
    resource :bookmarks, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get :join
    end
    member do
      get :withdrawal
    end
    resources :chat_messages, only: [:index, :create]
  end
  resources :categories, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
                
  has_one_attached :image, dependent: :destroy
  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users
  has_many :chat_messages
  has_many :direct_room_users
  has_many :direct_rooms, through: :direct_room_users
  has_many :direct_messages
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower
  has_many :likes
  has_many :chat_rooms_like, class_name: 'ChatRooms', through: :likes
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  
  validates :nickname, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX, on: :create

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :follows, :followers]
  before_action :set_follow, only: [:follows, :followers]
  before_action :notification_index, only: [:show, :check]
  before_action :direct_rooms_search, only: :show

  def show
    @user = User.find(params[:id])
    @chat_rooms = @user.chat_rooms
    @direct_rooms = @user.direct_rooms
    @following_users = @user.following_user
    @follower_users = @user.follower_user
    if user_signed_in?
      @bookmarks = Bookmark.where(user_id: current_user.id)
    end
  end

  def follows
  end
  
  def followers
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    if current_user.update(user_params)
      redirect_to user_path
      flash[:notice] = "更新しました"
    else
      render :edit
    end
  end

  def destroy_all
    user = User.find(params[:id])
    @notifications = current_user.passive_notifications.destroy_all
    redirect_to user_path(user)
  end

  def check
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  private

  def set_follow
    user = User.find(params[:id])
    @users_following = user.following_user.page(params[:page]).per(20).order('updated_at DESC')
    @users_follower = user.follower_user.page(params[:page]).per(20).order('updated_at DESC')
  end

  def user_params
    params.require(:user).permit(:nickname, :email, :image, :profile)
  end

  def notification_index
    if user_signed_in?
      @notifications = current_user.passive_notifications
      @notifications = @notifications.where.not(visitor_id: current_user.id)
    end
  end

  def direct_rooms_search
    user = User.find(params[:id])
    direct_rooms = user.direct_rooms
    @dm_owner = direct_rooms.find_by(owner_id: current_user)
    @dm_another = direct_rooms.find_by(another_id: current_user)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def unchecked_notifications
    @search_notifications = current_user.passive_notifications.where(checked: false)
  end
  
end

app/views/users/_follow.html.erb
<% if user_signed_in? %>
<div class="follower">
  <%= link_to "フォロー", follows_user_path(@user), class:"follows" %>
  <div class="follower-count-box">
    <%= @following_users.count %>
  </div>    
</div>
<div class="followed">
  <%= link_to "フォロワー", followers_user_path(@user), class:"followers" %>
  <div class="follower-count-box">
    <%= @follower_users.count %>
  </div>
</div>
<div class="followed-botton-area">
  <% if current_user != @user %>
    <% if current_user.following?(@user) %>
    <div class="followed-botton">
      <%= link_to 'フォローを外す', user_relationships_path(@user.id), method: :delete, class: "f-btn danger", remote: true %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(@user.id), method: :post, class:"f-btn success", remote: true %>
    </div>
    <% end %>
  <% end %>
</div>
<% end %>

app/views/users/edit.html.erb
<div class="user-edit-container">
  <div class="edit-heading">
    <p class="edit-text">マイページの編集</p>
  </div>
  <div class="edit-main">
    <div class="edit-wrap">
      <%= form_with model: @user, id: "user_form", url: user_path, class: 'registration-from', local: true do |f| %>
        <div class="edit-area">
          <p class="edit-profile-content">ニックネームの変更</p>
          <div class="edit-input-area">
            <%= f.text_field :nickname, class:"edit-nickname-input", placeholder:"ニックネームを記入", maxlength:"25" %>
          </div>
        </div>
        <div class="edit-area">
          <p class="edit-profile-content">メールアドレスの変更</p>
          <div class="edit-input-area">
            <%= f.text_field :email, class:"edit-nickname-input", placeholder:"メールアドレスを記入", maxlength:"25" %>
          </div>
        </div>
        <div class="edit-area">
          <p class="edit-profile-content">プロフィールアイコンの設定</p>
          <div class="image-previews-area">
            <div class="image-previews">
              <div id="previews"></div>
            </div>
          </div>
          <div class="edit-image">
            <%= f.label :image, "画像をアップロード", class: "edit-image-input-btn", id:"item-image" %>
            <%= f.file_field :image, class: "image-form" %>
          </div>
          <p class="edit-profile-content">プロフィールの編集</p>
          <div class="edit-input-area">
            <%= f.text_area :profile, class:"edit-profile-input", placeholder:"プロフィールを記入" %>
          </div>
          <div class="btn-area">
            <%= f.submit "更新する" ,class:"click-botton" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
    

app/views/users/followers.html.erb
<div class="follow-container">
  <%= render "shared/follows" %>
  <%= render "shared/followers" %>
</div>

app/views/users/follows.html.erb
<div class="follow-container">
  <%= render "shared/follows" %>
  <%= render "shared/followers" %>
</div>

app/views/users/show.html.erb
<div class="mypage-container">
  <div class="text-success-area-user">
    <span class="text-success-user"><%= flash[:notice] %></span>
  </div>
  <div class="mypage-contents">
    <div class="my-box">
      <div class="my-heading"><%= "#{@user.nickname}さんのマイページ" %></div>
    </div>
    <div class="email-box">
      <% if user_signed_in? %>
        <% unless @user.id == current_user.id %>
          <% unless @dm_owner.present? || @dm_another.present? %>
            <%= link_to image_tag("email.png", class:"menu-image"), new_user_direct_room_path(@user) %>
          <% end %>
        <% end %> 
        <% if @user.id == current_user.id %>
          <%= image_tag("bookmark.png", class:"menu-image", id:"bookmark")%>
          <div class="bookmark-index hidden" id="bookmark-wrap">
            <div class="notification-text-area">
              <%= image_tag("return.png", class:"return-btn", id:"return-btn-bookmark")%>
              <p class="bookmark-text">お気に入り一覧</p>
            </div>
            <div class="text-border"></div>
            <div class="bookmark-contents">
              <% if @bookmarks.exists? %>
                <% @bookmarks.each do |bookmark| %>
                  <%= link_to bookmark.chat_room.name, chat_room_path(bookmark.chat_room), class:"chat-room-text-bookmark"%>
                <% end %>
              <% else %>
                <p class="notification-nil">お気に入りはありません</p>
              <% end %>
            </div>
          </div>
          <% if unchecked_notifications.any? %>
            <span class="notifications-count"><%= @notifications.count %></span>
          <% end %>
          <%= link_to image_tag("notification.png", class:"menu-image", id:"notification-btn"), check_user_path, remote: true %>
          <div class="notification hidden" id="notification-wrap">
            <div class="notification-wrap">
              <div class="notification-text-area">
                <%= image_tag("return.png", class:"return-btn", id:"return-btn")%>
                <p class="notification-text">通知一覧</p>
              </div>
              <div class="text-border"></div>
              <% if @notifications.exists? %>
                <div class="users-index">
                  <%= render partial: "shared/notification", collection: @notifications %>
                </div>
                <% else %>
                    <p class="notification-nil">通知はありません</p>
                <% end %>
                <% if @notifications.present? %>
                  <%= link_to image_tag("garbage.png", class:"garbage"), destroy_all_user_path, data: { 'turbolinks': false } %>
                  <p class="notification-destroy">通知を全件削除</p>
                <% end %>
            </div>
          </div>
          <%= link_to image_tag("edit.png", class:"menu-image"), edit_user_path, data: { 'turbolinks': false } %>
        <% end %>
      <% end %>
      <%= link_to image_tag("home.png", class:"menu-image"), root_path %>
    </div>
    <div class="user-image-area">
      <p class= "profile-text">Profile</p>
      <% if @user.image.present? %>
      <div class="image-display">
        <div class="image-outer">
          <div class="image-item">
            <%= image_tag(@user.image, class:"user-image") %>
          </div>
        </div>
      </div>
      <% else %>
        <div class="image-nill-display">
          <div class="image-nill-outer">
            <p class="image-nill-item">no<br>image<p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="profile-area">
      <div class="profile">
        <%= @user.profile %>
      </div>
    </div>
    <div class="selection-field" id="follow">
      <%= render "follow" %>
    </div>
  </div>
  <%= render "shared/user_index_rooms"%>
</div>