config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'chat_rooms#index'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follows, :followers
    end
    member do
      get :destroy_all
    end
    member do
      get :check
    end
    resource :relationships, only: [:create, :destroy]
    resources :direct_rooms, only: [:new, :create, :destroy] do
      resources :direct_messages, only: [:index, :create]
    end
  end
  resources :chat_rooms do
    resource :bookmarks, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get :join
    end
    member do
      get :withdrawal
    end
    resources :chat_messages, only: [:index, :create]
  end
  resources :categories, only: [:index]
end

app/views/shared/_book_mark.html.erb
<div class="book-mark-wrap">
  <% if @chat_room.bookmarked_by?(current_user) %>
    <div class="book-mark-area">
      <p class="book-mark-ster">★</p>
      <%= link_to "お気に入り削除", chat_room_bookmarks_path(@chat_room), method: :delete, class:"book-mark-text", remote: true %>
    </div>
  <% else %>
    <div class="book-mark-area-nil">
      <p class="book-mark-ster-nil">★</p>
      <%= link_to "お気に入りに登録", chat_room_bookmarks_path(@chat_room), method: :post, class:"book-mark-text", remote: true %>
    </div>
  <% end %>
</div>

app/views/shared/_chat_message.html.erb
<div class="chat-message-user">
  <div class="message-user-name">
    <%= chat_message.user.nickname %>
  </div>
  <div class="message-time">
     <%= chat_message.created_at.to_s(:datetime_jp) %>
     <% wdays = ['( 日 )','( 月 )','( 火 )','( 水 )','( 木 )','( 金 )','( 土 )'] %>
     <% day = chat_message.created_at.to_s(:wday_jp) %>
     <span class="wdays"><%= wdays[day.to_i]%></span>
  </div>
</div>
<div class="chat-message-contents">
  <% if chat_message.content.present? %>
    <span class="message-content" >
      <%= chat_message.content %>
    </span>
  <% end %>
</div>
<div class="chat-message-contents">
  <div class="messages">
    <%= image_tag chat_message.image.variant(resize: '500x500'), class: "chat-message-image" if chat_message.image.attached? %>
  </div>
</div>

app/views/shared/_direct_message.html.erb
<div class="chat-message-user">
  <div class="message-user-name">
    <%= direct_message.user.nickname %>
  </div>
  <div class="message-time">
    <%= direct_message.created_at.to_s(:datetime_jp) %>
    <% wdays = ['( 日 )','( 月 )','( 火 )','( 水 )','( 木 )','( 金 )','( 土 )'] %>
    <% day = direct_message.created_at.to_s(:wday_jp) %>
    <span class="wdays"><%= wdays[day.to_i]%></span>
  </div>
</div>
<div class="chat-message-contents">
  <% if direct_message.content.present? %>
    <span class="message-content" >
      <%= direct_message.content %>
    </span>
  <% end %>
</div>
<div class="chat-message-contents">
  <div class="messages">
    <%= image_tag direct_message.image.variant(resize: '500x500'), class: "chat-message-image" if direct_message.image.attached? %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
   <ul>
     <% model.errors.full_messages.each do |message| %>
       <li class='error-message'><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/shared/_followers.html.erb
<div class="followers-wrap">
  <p class="fw text">フォロワー list</p>
  <div class="fw-area">
    <div class="list followers">
    <% @users_follower.each do |user_f| %>
      <div class="user-contents">
      <% if user_f.image.present?%>
        <%= image_tag(user_f.image, class: "image-users")%>
      <% else %>
        <%= image_tag("nil-image.png", class: "image-users")%>
      <% end %>
      <%= link_to user_f.nickname, user_path(user_f), class:"fw-nickname" %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/shared/_follows.html.erb
<div class="follows-wrap">
  <p class="fw text">フォロー list</p>
  <div class="fw-area">
    <div class="list follows">
      <% @users_following.each do |user_f| %>
        <div class="user-contents">
        <% if user_f.image.present?%>
          <%= image_tag(user_f.image, class: "image-users")%>
        <% else %>
          <%= image_tag("nil-image.png", class: "image-users")%>
        <% end %>
        <%= link_to user_f.nickname, user_path(user_f), class:"fw-nickname" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <%= image_tag("room-frends.png", class:"room-frends") %>  
  <small>© Shumitomo 2022</small>
  <%= image_tag("frends.png", class:"frends") %>
</div>

app/views/shared/_header.html.erb
<header class="header-area">
  <div class="header-contents">
    <div class="title-name">
      <%= link_to image_tag("title-logo.jpg", class:"title-icon"), root_path %>
    </div>
    <%= form_with(url: search_chat_rooms_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "キーワードを入力", class: "input-box" %>
      <%= form.submit "検索", class: "submit-search" %>
    <% end %>
    </form>
    <div class="devise-lists">
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, "/users/#{current_user.id}", class: "user-nickname" , data: { 'turbolinks': false } %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </div>
  </div>
  <ul class="category-lists">
    <% @genres.each do |category| %>
      <li><%= link_to category.name, categories_path(category_id: category.id), class: "set"%></li>
    <% end %>
  </ul>
  <div class="text-success-area">
    <span class="text-success"><%= flash[:notice] %></span>
  </div>
</header>

app/views/shared/_like.html.erb
<% if @chat_room.liked?(current_user) %>
  <div class="like-area">
    <%= image_tag("like.png", class:"like-image") %>
    <%= link_to "いいね", chat_room_likes_path(@chat_room), class:"like-text", method: :delete, remote: true %>
    <span class="likes-count"><%= @chat_room.likes.count %></span>
  </div>
<% else %>
  <div class="like-area">
    <%= image_tag("like.png", class:"like-image") %>
    <%= link_to "いいね", chat_room_likes_path(@chat_room), class:"like-text", method: :post, remote: true %>
    <span class="likes-count"><%= @chat_room.likes.count %></span>
  </div>
<% end %>

app/views/shared/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="notification-main">
  <div class="notification-contents">
    <% if visitor.image.present? %>
      <%= image_tag(visitor.image, class: "notification-visitor-image")%>
    <% end %>
    <%= link_to visitor.nickname, user_path(visitor), class:"visitor-nickname"%>
    <% if notification.direct_message %>
      <p class="later-text">さんから</p>
    <% else %>
      <p class="later-text">さんが</p>
    <% end %>
    <% case notification.action %>
    <% when 'follow' then %>
      <p class="visited-notification-text"><span class="visited">あなたを</span>フォローしました</p>
    <% when 'like' then %>
        <%= link_to "あなたのチャットルーム", notification.chat_room, class:"visited", data: { 'turbolinks': false } %>
        <p class="visited-notification-text">にいいねしました</p>
    <% when 'chat_message' then %>
      <% chat_room = notification.chat_room %>
      <% if notification.chat_room.owner_id == visited.id %>
        <%= link_to "あなたのチャットルーム", chat_room_chat_messages_path(chat_room), class:"visited" %>
        <p class="visited-notification-text">に投稿しました</p>
      <% else %>
        <%= link_to chat_room.name, chat_room_chat_messages_path(chat_room), class:"visited" %>
        <p class="visited-notification-text">に投稿しました</p>
        <span class="visitor-message"><%= notification.chat_message.content %></span>
      <% end %>
    <% when 'direct_message' then %>
      <% direct_room = notification.direct_room_id %>
      <%= link_to "DM", user_direct_room_direct_messages_path(@user, direct_room), class:"visited" %>
      <p class="visited-notification-text">が届きました</p>
      <span class="visitor-message"><%= notification.direct_message.content %></span>
    <% end %>
    <span class="moderate-font"><%= "#{time_ago_in_words(notification.created_at)}前" %></span>
  </div>
</div>

app/views/shared/_second-header.html.erb
<div class="second-header-wrapper">
  <div class="title-content">
    <%= link_to image_tag("title-logo.jpg", class:"title-icon"), root_path %>
  </div>

app/views/shared/_side_chat.html.erb
<div class="side-chat-wrap">
  <div class="user-text">User list</div>
  <div class="users-name-area">
    <% @chat_room_user.each do |c| %>
      <div class="chat-index-users-area">
        <% if c.user.image.present?%>
          <%= image_tag(c.user.image, class: "image-users")%>
        <% else %>
          <%= image_tag("nil-image.png", class: "image-users")%>
        <% end %>
        <%= link_to c.user.nickname, user_path(c.user), class:"user-names", data: { 'turbolinks': false } %>
      </div>  
    <% end %>
  </div>
</div>

app/views/shared/_user_index_rooms.html.erb
<div class="room-wrapper">
  <div class="room-area">
    <p class="room-text">チャットルーム一覧</p>  
    <div class="rooms">
      <% @chat_rooms.each do |chat_room| %>
        <div class="room-name-put">
          <%= link_to chat_room.name, chat_room_path(chat_room), class:"room", data: { 'turbolinks': false } %>
        </div>
      <% end %>
    </div>
  </div>
  <% if user_signed_in? %>
    <% if @user.id == current_user.id %>
      <div class="room-area" id="dm-list">
        <p class="room-text">DMルーム一覧</p>  
        <div class="rooms">
          <% @direct_rooms.each do |direct_room| %>
            <div class="room-name-put">
              <%= link_to direct_room.subject, user_direct_room_direct_messages_path(@user, direct_room), class:"room" %>
              <% direct_room.users.where.not(id: current_user.id).each do |user| %>
                <span class="dm-user-nickname"><%= link_to user.nickname, user_path(user), class:"dm-user-link-text" %>さん</span>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>