config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'chat_rooms#index'
  resources :users, only: [:show, :edit, :update] do
    member do
      get :follows, :followers
    end
    member do
      get :destroy_all
    end
    member do
      get :check
    end
    resource :relationships, only: [:create, :destroy]
    resources :direct_rooms, only: [:new, :create, :destroy] do
      resources :direct_messages, only: [:index, :create]
    end
  end
  resources :chat_rooms do
    resource :bookmarks, only: [:create, :destroy]
    resource :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    member do
      get :join
    end
    member do
      get :withdrawal
    end
    resources :chat_messages, only: [:index, :create]
  end
  resources :categories, only: [:index]
end

app/models/direct_room.rb
class DirectRoom < ApplicationRecord

  has_many :direct_room_users, dependent: :destroy
  has_many :users, through: :direct_room_users
  has_many :direct_messages, dependent: :destroy
  has_many :notifications, dependent: :destroy

  validates :subject, presence: true

end

app/controllers/direct_rooms_controller.rb
class DirectRoomsController < ApplicationController
  before_action :authenticate_user!, only: :new

  def new
    @direct_room = DirectRoom.new
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    @direct_room = DirectRoom.new(direct_room_params)
    if @direct_room.save
      redirect_to user_direct_room_direct_messages_path(@user, @direct_room)
    else
      render :new
     end
  end

  def destroy
    direct_room_user = DirectRoomUser.find_by(direct_room_id: params[:id])
    @direct_room_user = direct_room_user.direct_room
    if @direct_room_user.destroy
      redirect_to root_path
      flash[:notice] = "DMルームを閉じました"
    end
  end

  private
   
    def direct_room_params
      params.require(:direct_room).permit(:owner_id, :another_id, :subject, [user_ids: []]).merge(owner_id: current_user.id, another_id: @user.id)
    end
end

app/helpers/direct_rooms_helper.rb
module DirectRoomsHelper
end

app/views/direct_rooms/new.html.erb
<%= render "shared/second-header"%>

<div class="dm-container">
  <div class="room-main">
    <div class="dm-heading-area">
      <div class="heading">DMルーム作成</div>
    </div>
    <%= form_with model: [@user, @direct_room], url: user_direct_rooms_path, class: 'registration-from', local: true do |f| %>
      <div class="dm-user-info">
        <%= f.text_field :subject, class:"subject-input", placeholder:"件名を記入して下さい", maxlength:"45" %>
        <p class="info-text"><%= @user.nickname %>さんとDMを始めますか？</p>
      </div>
      <input name="direct_room[owner_id, another_id][]" type="hidden" value=<%= @user.id %>>
      <input name="direct_room[user_ids][]" type="hidden" value=<%= @user.id %>>
      <input name="direct_room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      <div class="dm-btn-area">
        <%= f.submit "始める" ,class:"click-botton" %>
      </div>
    <% end %>
  </div>
</div>